// ═══════════════════════════════════════════
// FSW DATA — Source of Truth
// Update wrestlers here. All pages read from this file.
// ═══════════════════════════════════════════

const wrestlers = [
  {
    name: "Shibata Reyes",
    incomplete: false,
    nickname: "The Founding Father",
    img: "https://i.imgur.com/8sYtF4l.jpeg",
    popupImg: "https://i.imgur.com/8sYtF4l.jpeg",
    bgImg: "https://i.imgur.com/8Ff7wJD.jpeg",
    videoId: "TSKPLwFDaKI",
    alignment: "heel",
    champion: true,
    title: "FSW Ultima Champion",
    location: "Los Angeles, CA",
    height: "5'11\"",
    weight: "228 lbs",
    stable: "Leader of Umbra Collective · Longest Reigning FSW Champion in History · Iron 50 Trophy Winner",
    rival: "Kendrick Montana · Anthony Ragone · Derrick Maximus · Aric Myers · TJ Frost",
    allies: "Chris Jackson · Jeremiah Brown · Cola Davis · Ivy Page",
    social: "@fswyoutub.shibata",
    theme: "The Foundations of Decay — My Chemical Romance",
    rating: 93,
    endorsements: ["GEICO", "Norton LifeLock", "Tap Out", "Beats by Dre"],
    commercials: [
      { brand: "GEICO", videoId: "KOBAqcMw2nU" },
      { brand: "Norton LifeLock", videoId: "Dau5JpQQwOQ" },
    ],
    movies: [
      { title: "Street Fighter", released: "March 2026", videoId: "raPQD-uwWL8", role: "Vega" },
    ],
    debut: "FSW 1: Maximum",
    record: { singlesW:7, singlesL:1, multiW:3, multiL:0, titleWins:2, titleDefenses:2 },
    bio: "Shibata Reyes is the reigning FSW Ultima Champion and the cold, commanding leader of the Umbra Collective. Methodical, ruthless, and always ten steps ahead — Shibata doesn't just win matches, he dismantles legacies.",
    finisher1: "Street Justice",
    finisher1Orig: "Judo Throw DDT",
    finisher2: "Reyes Lock",
    finisher2Orig: "Crossface",
    signatures: [["Superkick","Mercy Kick"],["Coast to Coast","Tree of Woke"]],
    titleHistory: [
      { title: "FSW Ultima Championship", event: "FSW 50: Nemesis", date: "09.09.25" },
      { title: "FSW Bloodsport Championship", event: "FSW 1: Maximum" },
    ],
    accolades: ["Iron 50 Trophy Winner"],
    factions: [
      {
        name: "The Umbra Collective",
    incomplete: true,
        logo: "https://i.imgur.com/HdOBaGI.png",
        role: "Leader",
        members: ["Shibata Reyes", "CJ Moore", "Ivy Page"],
        motto: "Umbra is only for those willing to abandon what once defined them.",
        debut: "FSW 50: Nemesis",
      }
    ],
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Kendrick Montana", result:"L", type:"Singles", championship:"FSW Ultima Championship", ranked:true, rankPos:3 },
    { show:"FSW 51: Victory", opponent:"Derrick Maximus", result:"W", type:"Singles — DQ", championship:"FSW Ultima Championship", ranked:true, rankPos:3 },
    { show:"FSW 50: Nemesis", opponent:"Anthony Ragone", result:"W", type:"Singles", championship:"FSW Ultima Championship", ranked:true, rankPos:3 }
  ],
  },
  // ↓ Add more wrestlers below ↓
  {
    name: "Vincent Omen",
    incomplete: false,
    nickname: "The Villain King",
    img: "https://i.imgur.com/QOm1XAf.jpeg",
    popupImg: "https://i.imgur.com/QOm1XAf.jpeg",
    bgImg: "",
    videoId: "-LuYgWiFvHk",
    champion: false, title: "",
    alignment: "heel",
    location: "Dublin, Ireland",
    height: "6'0\"", weight: "269 lbs",
    stable: "The Syndicate",
    social: "@fswyoutub.vincent", twitter: "@VMFO_420", twitterUrl: "https://x.com/VMFO_420", instagram: "",
    theme: "Violence No Matter What",
    rating: 84, rival: "",
    endorsements: ["Jameson Whiskey"],
    bio: "Vincent Omen carries an ominous calm that makes every situation feel uneasy. As a member of the Syndicate alongside Damian Rage, he operates with quiet loyalty and calculated intent, letting others underestimate him before revealing how dangerous he truly is. Vincent Omen does not chase chaos; he waits for the right moment to tip the balance in the Syndicate's favor.",
    signatures: [["RKO 1", "VKO"], ["Clothesline from Hell", "Get F**ked"]],
    finisher1: "Rabbit Hole", finisher1Orig: "Last Shot 2",
    finisher2: "Dead Man's Wonderland", finisher2Orig: "Dragon Twist Cutter",
    superFinisher: "VKO", superFinisherOrig: "Avalanche RKO",
    factions: [
      {
        name: "The Syndicate",
        logo: "https://i.imgur.com/wHYCnuS.png",
        role: "Member",
        members: ["Damian Rage", "Vincent Omen", "Brittany Black"],
        motto: "Burn the order. Build the Syndicate.",
        debut: "FSW 19: Nemesis",
      }
    ],
    debut: "FSW 19: Nemesis",
    record: { singlesW:2, singlesL:1, multiW:2, multiL:1, titleWins:1, titleDefenses:1 },
  },
  {
    name: "Axel Hernandez",
    incomplete: false,
    nickname: "",
    img: "https://i.imgur.com/WUg18jX.jpeg",
    popupImg: "https://i.imgur.com/WUg18jX.jpeg",
    bgImg: "",
    videoId: "n9h7hU6_VI4",
    champion: false, title: "",
    alignment: "tweener",
    location: "San Juan, Puerto Rico",
    height: "6'1\"", weight: "287 lbs",
    stable: "", social: "@fswyoutub.axel", twitter: "@AxelHernandes", instagram: "",
    theme: "Animal I Have Become — Three Days Grace", rating: 82, rival: "",
    endorsements: ["Takis", "Slim Jim"],
    bio: "Axel Hernandez fights with dangerous intent and little regard for convention. Known for relying on weapons whenever the opportunity presents itself, he turns matches into chaotic battlegrounds where control quickly slips away. Axel does not just want to win; he wants opponents to feel the damage long after the bell rings, making him one of the most unpredictable and feared competitors in FSW.",
    signatures: ["Superkick", "Small Package Piledriver"],
    finisher1: "BFT", finisher1Orig: "BFT",
    superFinisher: "World's Strongest Slam", superFinisherOrig: "World's Strongest Slam",
    debut: "FSW 51: Victory",
    record: { singlesW:0, singlesL:2, multiW:0, multiL:0, titleWins:0, titleDefenses:0 },
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Matheo", result:"L", type:"Singles", championship:null, ranked:false, rankPos:null },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "Blade Rivera",
    incomplete: false,
    nickname: "",
    img: "https://i.imgur.com/EJKJ1B9.jpeg",
    popupImg: "https://i.imgur.com/EJKJ1B9.jpeg",
    bgImg: "",
    videoId: "BKNi2ivRAPo",
    champion: false, title: "",
    alignment: "face",
    location: "Denver, CO",
    height: "6'0\"", weight: "228 lbs",
    stable: "", social: "", instagram: "",
    theme: "Stitches — Orgy", rating: 83, rival: "",
    endorsements: ["5-Hour Energy"],
    bio: "Blade Rivera fights with sharp intensity and relentless determination. Known for his aggressive pace and fearless approach, he pushes every match forward, forcing opponents to keep up with his energy or fall behind. Blade Rivera thrives in high-pressure situations, using speed, grit, and precision to turn every opportunity into a decisive moment.",
    signatures: ["Calf Crusher", "Springboard 630 Senton"],
    finisher1: "Juggernaut Driver", finisher1Orig: "Juggernaut Driver",
    finisher2: "Lo Down", finisher2Orig: "Lo Down",
    debut: "FSW 51: Victory",
    record: { singlesW:0, singlesL:2, multiW:0, multiL:0, titleWins:0, titleDefenses:0 },
  },
  {
    name: "Brittany Black",
    incomplete: false,
    nickname: "",
    img: "https://i.imgur.com/ptBVk3Z.jpeg",
    popupImg: "https://i.imgur.com/ptBVk3Z.jpeg",
    bgImg: "",
    videoId: "s2fbQw5iIdw",
    champion: false, title: "",
    alignment: "heel",
    location: "Green Bay, WI",
    height: "5'4\"", weight: "123 lbs",
    stable: "The Syndicate", social: "@fswyoutub.brittany", instagram: "",
    theme: "B.M.F. — Upon a Burning Body", rating: 85, rival: "",
    endorsements: ["Amiri", "Versace"],
    commercials: [
      { brand: "Amiri", videoId: "7ZbUjsWeB3U" },
    ],
    factions: [
      {
        name: "The Syndicate",
        logo: "https://i.imgur.com/wHYCnuS.png",
        role: "Member",
        members: ["Damian Rage", "Vincent Omen", "Brittany Black"],
        motto: "Burn the order. Build the Syndicate.",
        debut: "FSW 19: Nemesis",
      }
    ],
    bio: "Brittany Black is a rebel at heart, carrying a punk, anarchist attitude that refuses to follow anyone else's rules. She thrives on disruption, turning chaos into momentum while feeding off the energy of the crowd and the tension of the moment. Brittany does not fight for approval or tradition; she fights to tear down expectations and prove that unpredictability can be just as powerful as discipline.",
    debut: "FSW 37: Fight for Survival",
    record: { singlesW:0, singlesL:1, multiW:0, multiL:0, titleWins:0, titleDefenses:0 },
  },
  {
    name: "CJ Moore",
    incomplete: false,
    nickname: "",
    img: "https://i.imgur.com/TF7KcDi.jpeg",
    popupImg: "https://i.imgur.com/TF7KcDi.jpeg",
    bgImg: "https://i.imgur.com/FUh8rZ5.jpeg",
    videoId: "BGFxbzdJIwM",
    champion: true, title: "FSW First Class Champion",
    alignment: "heel",
    location: "Pittsburgh, PA",
    height: "5'10\"", weight: "228 lbs",
    stable: "Umbra Collective", social: "@fswyoutub.cj", twitter: "@I_Cyoung", instagram: "",
    theme: "Onna Come Up (Remix ft. G Herbo) — Lil Eazzyy", rating: 87, rival: "",
    endorsements: ["Carnival Cruise", "Doritos"],
    commercials: [
      { brand: "Carnival Cruise", videoId: "59R3kXSWgjs" },
    ],
    bio: "CJ Moore found himself pulled into the Umbra Collective before fully understanding what it demanded. Manipulated into joining a dangerous circle where loyalty is tested and choices carry consequences, CJ now walks a difficult line between ambition and survival. Whether he ultimately embraces Umbra's ruthless philosophy or finds a way out remains one of the most unpredictable stories unfolding in FSW.",
    titleHistory: [
      { title: "FSW First Class Championship", event: "FSW 51: Victory", date: "19.12.25", label: "Won" },
    ],
    factions: [
      {
        name: "The Umbra Collective",
        logo: "https://i.imgur.com/HdOBaGI.png",
        role: "Member",
        members: ["Shibata Reyes", "CJ Moore", "Ivy Page"],
        motto: "Umbra is only for those willing to abandon what once defined them.",
        debut: "FSW 50: Nemesis",
      }
    ],
    debut: "FSW 19: Nemesis",
    record: { singlesW:3, singlesL:4, multiW:1, multiL:3, titleWins:1, titleDefenses:0 },
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Damian Rage", result:"L", type:"FSW First-Class Championship", championship:"FSW First-Class Championship", ranked:false, rankPos:null },
    { show:"FSW 51: Victory", opponent:"—", result:"W", type:"Title Win", championship:"FSW First-Class Championship", ranked:true, rankPos:3 },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "Dean Ivy",
    incomplete: true,
    nickname: "",
    img: "https://i.imgur.com/wPn0GJT.png",
    popupImg: "https://i.imgur.com/wPn0GJT.png",
    bgImg: "",
    videoId: "",
    champion: false, title: "",
    alignment: "face",
    location: "",
    height: "", weight: "",
    stable: "", social: "", instagram: "",
    theme: "", rating: 85, rival: "",
    endorsements: ["Spotify"],
    bio: "Dean Ivy enters FSW as a determined newcomer eager to prove she belongs among the roster. Focused and observant, she approaches every match as a chance to learn, adapt, and make her presence known. While still building her reputation, Dean Ivy's discipline and resilience suggest a competitor with the potential to rise quickly and make a lasting impact.",
    record: { singlesW:0, singlesL:0, multiW:0, multiL:0, titleWins:0, titleDefenses:0 },
  },
  {
    name: "Henry Carter",
    incomplete: false,
    nickname: "",
    img: "https://i.imgur.com/rZksJJN.jpeg",
    popupImg: "https://i.imgur.com/rZksJJN.jpeg",
    bgImg: "",
    videoId: "GZN6ISY_0e8",
    champion: false, title: "",
    alignment: "face",
    location: "England",
    height: "6'5\"", weight: "260 lbs",
    stable: "", social: "@fswyoutub2.henry", instagram: "thehcarter",
    theme: "On My Own — Three Days Grace", rating: 85, rival: "",
    endorsements: ["Jack Daniel's"],
    bio: "Henry Carter carries himself with composed confidence and old-school toughness. He approaches every match with discipline and patience, preferring steady control over reckless aggression. Henry Carter is the kind of competitor who stays grounded under pressure, relying on experience and resilience to outlast opponents when the fight gets difficult.",
    debut: "FSW 52: Maximum",
    record: { singlesW:1, singlesL:0, multiW:0, multiL:0, titleWins:0, titleDefenses:0 },
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Javi Hernandez", result:"W", type:"Singles — Show opener", championship:null, ranked:false, rankPos:null },
    { show:"FSW 51: Victory", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "JB Hayes",
    incomplete: false,
    nickname: "",
    img: "https://i.imgur.com/xG7y9Li.jpeg",
    popupImg: "https://i.imgur.com/xG7y9Li.jpeg",
    bgImg: "",
    videoId: "N-3WpISlQCE",
    champion: false, title: "",
    alignment: "tweener",
    location: "Vallejo, CA",
    height: "6'3\"", weight: "225 lbs",
    stable: "", social: "@JBHayes707", instagram: "",
    theme: "Crest Shit or No Shit — Dubee", rating: 84, rival: "",
    endorsements: ["Jack in the Box"],
    bio: "JB Hayes competes with gritty determination and relentless drive. Known for pushing through punishment without hesitation, he thrives in hard-fought battles where endurance and toughness matter most. JB Hayes does not rely on flash or theatrics; he wins respect by outlasting opponents and proving he can endure more than anyone standing across from him.",
    record: { singlesW:2, singlesL:1, multiW:0, multiL:1, titleWins:0, titleDefenses:0 },
  },
  {
    name: "KJ Hunter",
    incomplete: false,
    nickname: "The One And Only Icon, Phenomenal One",
    img: "https://i.imgur.com/deVWV7G.jpeg",
    popupImg: "https://i.imgur.com/deVWV7G.jpeg",
    bgImg: "https://i.imgur.com/xp86QD5.jpeg",
    videoId: "",
    champion: false, title: "",
    alignment: "face",
    location: "Montgomery, Alabama",
    height: "6'1\"", weight: "190 lbs",
    stable: "", social: "@fswyoutub.kj", instagram: "",
    theme: "", rating: 85, rival: "The Syndicate",
    allies: ["Travis Valentine"],
    endorsements: ["Caesar's Rewards", "DraftKings", "Ignite Wireless"],
    bio: "KJ Hunter carries a carefree attitude that hides a dangerous secret. A natural risk-taker with a love for gambling, he treats life and competition the same way, trusting instinct and luck more than discipline. Many around him believe his talent is being wasted because he refuses to take things as seriously as he could, yet the flashes of brilliance he shows make it clear that KJ Hunter possesses far more potential than he chooses to reveal.",
    signatures: [["Air Raid Crash Neckbreaker 4", "Equalizer"]],
    finisher1: "Hunter Clash", finisher1Orig: "Styles Clash 1",
    commercials: [
      { brand: "Caesar's Rewards", videoId: "KlDu_5Mnq3g" },
      { brand: "Ignite Wireless", videoId: "FeGkDz8n0LU" },
      { brand: "DraftKings", videoId: "kJ-0lyvYdrw" },
    ],
    movies: [
      { title: "Street Fighter", released: "March 2026", videoId: "raPQD-uwWL8", role: "Dee Jay" },
    ],
    record: { singlesW:1, singlesL:5, multiW:0, multiL:4, titleWins:0, titleDefenses:0 },
  },
  {
    name: "Matheo",
    incomplete: false,
    nickname: "The French General",
    img: "https://i.imgur.com/5UWC3F8.jpeg",
    popupImg: "https://i.imgur.com/5UWC3F8.jpeg",
    bgImg: "",
    videoId: "rm-Itwve0l4",
    champion: false, title: "",
    alignment: "heel",
    location: "France",
    height: "6'5\"", weight: "241 lbs",
    stable: "", social: "@fswyoutub.matheo", instagram: "",
    theme: "Fashion EDM Technology — Infraction", rating: 86, rival: "",
    endorsements: ["Denny's", "Monster Energy"],
    commercials: [
      { brand: "Monster Energy", videoId: "oEpiRn82Dn4" },
    ],
    bio: "Matheo brings natural confidence and sharp instincts into every match. Quick on his feet and fearless in competition, he thrives in fast exchanges where timing and precision matter most. Matheo competes with the mindset of someone determined to rise through the ranks, using every opportunity to prove he belongs among the most dangerous names in FSW.",
    signatures: [["Sleeper Hold", "French Sleeper"], ["Superkick", "The French Kick"]],
    finisher1: "The French Law", finisher1Orig: "Powerbomb",
    finisher2: "The French Knee", finisher2Orig: "Trick Shot",
    superFinisher: "The French Splash", superFinisherOrig: "450 Splash",
    movies: [
      { title: "Street Fighter", released: "March 2026", videoId: "raPQD-uwWL8", role: "Guile" },
    ],
    debut: "FSW 52: Maximum",
    record: { singlesW:1, singlesL:0, multiW:0, multiL:0, titleWins:0, titleDefenses:0 },
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Axel Hernandez", result:"W", type:"Singles debut", championship:null, ranked:false, rankPos:null },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "Smoove Marino",
    incomplete: false,
    nickname: "",
    img: "https://i.imgur.com/SubN4je.jpeg",
    popupImg: "https://i.imgur.com/SubN4je.jpeg",
    bgImg: "",
    videoId: "HIxk-21co88",
    champion: false, title: "",
    alignment: "heel",
    location: "",
    height: "6'2\"", weight: "286 lbs",
    stable: "", social: "@JAHH444_MarinoX", instagram: "jahh_marino",
    theme: "Out Of My Hands — Future & Metro Boomin", rating: 87, rival: "",
    endorsements: ["Hennessy"],
    bio: "Smoove Marino walks back into FSW with a reputation that only grew while he was gone. Recently released from jail, he carries the same swagger and street-hardened confidence that made him dangerous before, but now with even more to prove. Smoove Marino does not just want his place back; he wants everyone to remember why his name still carries weight the moment he steps into the arena.",
    debut: "FSW Underground",
    record: { singlesW:2, singlesL:1, multiW:0, multiL:0, titleWins:0, titleDefenses:0 },
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Jay Cole", result:"W", type:"Singles", championship:null, ranked:true, rankPos:9 },
    { show:"FSW Underground", opponent:"—", result:"W", type:"Singles", championship:null, ranked:false, rankPos:null },
    { show:"FSW Underground", opponent:"—", result:"L", type:"Singles", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "TJG",
    incomplete: true,
    nickname: "",
    img: "https://i.imgur.com/wPn0GJT.png",
    popupImg: "https://i.imgur.com/wPn0GJT.png",
    bgImg: "",
    videoId: "",
    champion: false, title: "",
    alignment: "face",
    location: "",
    height: "", weight: "",
    stable: "", social: "", instagram: "",
    theme: "", rating: 82, rival: "",
    endorsements: ["Celsius"],
    bio: "",
    record: { singlesW:0, singlesL:0, multiW:0, multiL:0, titleWins:0, titleDefenses:0 },
  },
  {
    name: "Travis Valentine",
    incomplete: false,
    nickname: "The King of Carnage",
    img: "https://i.imgur.com/OIjhMn9.jpeg",
    popupImg: "https://i.imgur.com/OIjhMn9.jpeg",
    bgImg: "https://i.imgur.com/u59YTjH.jpeg",
    videoId: "",
    champion: false, title: "",
    alignment: "face",
    location: "Chicago, IL",
    height: "6'3\"", weight: "260 lbs",
    stable: "", social: "@fswyoutub.travis", twitter: "@Kingofcarnage_", twitterUrl: "https://x.com/Kingofcarnage_", instagram: "",
    theme: "Worked Up — PHIX", rating: 86, rival: "The Syndicate",
    allies: ["KJ Hunter"],
    endorsements: ["Budweiser", "Old Spice"],
    commercials: [
      { brand: "Budweiser", videoId: "NguNLcB4_78" },
    ],
    bio: "Travis Valentine carries a quiet menace that makes people uneasy the moment he appears. Calculated and unpredictable, he rarely wastes words, preferring to let tension build before choosing the exact moment to strike. Travis Valentine does not fight for attention or approval; he moves on his own terms, turning every encounter into a psychological battle where opponents often realize too late that they were being controlled all along.",
    finisher1: "Hollow Tip", finisher1Orig: "Bicycle Knee Strike 5",
    finisher2: "Head Tap", finisher2Orig: "Basement Back Kick",
    superFinisher: "Last Resort", superFinisherOrig: "Shooting Star Press",
    record: { singlesW:1, singlesL:2, multiW:0, multiL:3, titleWins:0, titleDefenses:0 },
  },
  {
    name: "Jason Prince",
    incomplete: false,
    nickname: "",
    img: "https://i.imgur.com/Buesjnb.jpeg",
    popupImg: "https://i.imgur.com/Buesjnb.jpeg",
    bgImg: "https://i.imgur.com/i6ScyZR.jpeg",
    videoId: "JJTxgByP38Y",
    champion: false,
    title: "",
    alignment: "face",
    location: "Paducah, KY",
    height: "6'2\"",
    weight: "235 lbs",
    stable: "",
    social: "@fswyoutub.jason",
    instagram: "",
    theme: "OPPS ft. Dave East — Jahlil Beats & CRMC",
    rating: 85,
    rival: "",
    endorsements: ["Snickers", "DoorDash"],
    tv: [
      { show: "Chopped", videoId: "8_HbvNx9fgA", network: "Food Network" },
    ],
    bio: "Jason Prince carries himself with polished confidence and natural star presence. Charismatic and composed, he understands how to control the spotlight while backing it up with smooth, disciplined in-ring ability. Jason Prince competes with the mindset that excellence is expected, blending style and skill to prove he belongs among the elite.",
    record: { singlesW:1, singlesL:1, multiW:0, multiL:0, titleWins:0, titleDefenses:0 },
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"The Godson", result:"W", type:"Pre-Show", championship:null, ranked:false, rankPos:null },
    { show:"FSW 51: Victory", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "The Godson",
    incomplete: false,
    nickname: "Supreme Purple Pimp",
    img: "https://i.imgur.com/7xoQ6wc.jpeg",
    popupImg: "https://i.imgur.com/7xoQ6wc.jpeg",
    bgImg: "https://i.imgur.com/ADW9kbO.jpeg",
    videoId: "e7Kpzv2N-so",
    champion: false,
    title: "",
    alignment: "face",
    location: "Hackensack, NJ",
    height: "6'4\"",
    weight: "254 lbs",
    stable: "",
    social: "@fswyoutub2.godson",
    instagram: "the_godson420",
    theme: "Original Theme",
    rating: 85,
    rival: "",
    endorsements: ["Kit Kat"],
    commercials: [
      { brand: "Kit Kat", videoId: "todpvYk-2ec" },
    ],    bio: "The Godson brings an easygoing charisma that instantly connects with the crowd. Carefree and naturally entertaining, he thrives on the energy of the arena, turning every moment into a show. Beneath that playful confidence is serious athletic ability, allowing him to back up the fun with explosive speed, agility, and highlight-reel performances when the match truly heats up.",
    record: { singlesW:0, singlesL:1, multiW:0, multiL:0, titleWins:0, titleDefenses:0 },
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Jason Prince", result:"L", type:"Pre-Show debut", championship:null, ranked:false, rankPos:null },
    { show:"FSW 51: Victory", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "Motor Hunter",
    incomplete: false,
    img: "https://i.imgur.com/HrBGrSR.jpeg",
    popupImg: "https://i.imgur.com/HrBGrSR.jpeg",
    bgImg: "https://i.imgur.com/KicZpLM.jpeg",
    videoId: "80A5qUOw4E0",
    champion: false,
    title: "",
    nickname: "",
    alignment: "heel",
    location: "Los Angeles, CA",
    height: "6'5\"",
    weight: "244 lbs",
    stable: "",
    social: "@fswyoutub.motor",
    twitter: "@kobewrightkw",
    twitterUrl: "https://x.com/kobewrightkw",
    instagram: "",
    theme: "Dead Reckoning — Ethan Meixsell",
    rating: 87,
    rival: "",
    endorsements: ["Red Bull"],
    bio: "Motor Hunter is a relentless force wrapped in raw toughness. Built like someone who has spent his life pushing through resistance, he brings a grinding, punishing style that wears opponents down over time. Motor Hunter does not rush for flashy moments; he keeps pressure constant, forcing mistakes and capitalizing on them with brutal efficiency until the fight inevitably tilts in his favor.",
    signatures: ["Blue Thunder Bomb", "Nightmare Pendulum Submission"],
    finisher1: "Final Turn",
    finisher1Orig: "TKO",
    finisher2: "Lights Out",
    finisher2Orig: "Kross Hammer",
    movies: [
      { title: "Street Fighter", released: "March 2026", videoId: "raPQD-uwWL8" , role: "Sagat" },
    ],
    debut: "FSW 18: New Revolution",
    record: { singlesW:6, singlesL:4, multiW:1, multiL:5, titleWins:1, titleDefenses:1 },
    titleHistory: [
      { title: "FSW Mayhem Championship", event: "FSW 28: Sin City Slam", date: "21.01.24" },
    ],
  },
  {
    name: "J1",
    incomplete: false,
    nickname: "The Hybrid",
    img: "https://i.imgur.com/opQQ1P2.jpeg",
    popupImg: "https://i.imgur.com/opQQ1P2.jpeg",
    bgImg: "",
    videoId: "lU75CjHBr6I",
    champion: false,
    title: "",
    alignment: "face",
    location: "Yorkshire, England",
    height: "6'3\"",
    weight: "240 lbs",
    stable: "",
    social: "@fswyoutub.j1",
    twitter: "@the_hybrid_j1_caw",
    twitterUrl: "https://x.com/the_hybrid_j1_caw",
    instagram: "",
    theme: "Make It Make Sense — A Day to Remember",
    rating: 87,
    rival: "",
    endorsements: ["Tag Heuer", "Dr. Martens"],
    bio: "J1 competes with quiet dominance and absolute control. He wastes no movement, imposes his pace on every match, and forces opponents to fight on his terms. J1 does not chase moments or reactions; he simply takes over, making victories feel less like surprises and more like inevitabilities.",
    movies: [
      { title: "Street Fighter", released: "March 2026", videoId: "raPQD-uwWL8", role: "Zangief" },
    ],
    debut: "FSW 51: Victory",
    record: { singlesW:2, singlesL:0, multiW:0, multiL:0, titleWins:0, titleDefenses:0 },
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Javi Hernandez", result:"W", type:"Genesis Tournament Final", championship:null, ranked:true, rankPos:8 },
    { show:"FSW 51: Victory", opponent:"—", result:"W", type:"Debut — Genesis Tournament R1", championship:null, ranked:true, rankPos:8 },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "Arnez Jackson",
    incomplete: false,
    img: "https://i.imgur.com/O1wRnvp.jpeg",
    popupImg: "https://i.imgur.com/O1wRnvp.jpeg",
    bgImg: "https://i.imgur.com/k8Fi3oU.jpeg",
    videoId: "TdRYRQNu4Mk",
    champion: false,
    title: "",
    nickname: "",
    alignment: "face",
    location: "Detroit, Michigan",
    height: "6'0\"",
    weight: "292 lbs",
    stable: "",
    social: "@fswoutub2.arnez",
    twitter: "",
    instagram: "arnezthegreatest",
    instagramUrl: "https://www.instagram.com/arnezthegreatest",
    theme: "Hail Mary — 2Pac",
    rating: 88,
    rival: "",
    endorsements: ["Hennessy"],
    bio: "Arnez Jackson brings controlled swagger backed by real toughness. He carries himself like someone who has had to earn every opportunity, blending athletic explosiveness with sharp instincts in the ring. Arnez feeds off pressure rather than shrinking from it, and when momentum swings his way, he turns it into a statement instead of just a win.",
    movies: [
      { title: "Street Fighter", released: "March 2026", videoId: "raPQD-uwWL8", role: "Balrog" },
    ],
    debut: "FSW 52: Maximum",
    record: { singlesW:1, singlesL:0, multiW:0, multiL:0, titleWins:0, titleDefenses:0 },
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Jaelyn Garcia", result:"W", type:"Singles", championship:null, ranked:true, rankPos:7 },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "Jaelyn Garcia",
    incomplete: false,
    img: "https://i.imgur.com/3toE2OU.jpeg",
    popupImg: "https://i.imgur.com/3toE2OU.jpeg",
    bgImg: "https://i.imgur.com/y9Q1g9B.jpeg",
    videoId: "gudHbKQOZXc",
    champion: false,
    title: "",
    nickname: "",
    alignment: "heel",
    location: "Chicago, Illinois",
    height: "5'11\"",
    weight: "204 lbs",
    stable: "",
    social: "@fswyoutub.jaelyn",
    twitter: "@woah1tzjae",
    twitterUrl: "https://x.com/woah1tzjae",
    instagram: "woah1tzjae",
    instagramUrl: "https://www.instagram.com/woah1tzjae",
    theme: "Lies — Evanescence",
    rating: 87,
    rival: "",
    allies: "Derrick Maximus",
    endorsements: ["Chili's"],
    commercials: [
      { brand: "Chili's", videoId: "DfG5a4r8Gog" },
      { brand: "Skechers", videoId: "3R7rg6YelGI" },
    ],
    bio: "Jaelyn Garcia moves with quiet confidence and sharp awareness. He studies opponents carefully, rarely wasting motion or emotion, and strikes with precision when the opening presents itself. Jaelyn does not rely on noise or theatrics; his composure and preparation make him especially dangerous in high-pressure moments where others start to unravel.",
    movies: [
      { title: "Street Fighter", released: "March 2026", videoId: "raPQD-uwWL8", role: "Sean" },
    ],
    record: { singlesW:0, singlesL:1, multiW:0, multiL:0, titleWins:0, titleDefenses:0 },
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Arnez Jackson", result:"L", type:"Singles", championship:null, ranked:false, rankPos:null },
    { show:"FSW 51: Victory", opponent:"—", result:"—", type:"Storyline", championship:null, ranked:false, rankPos:null },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "Javi Hernandez",
    incomplete: false,
    img: "https://i.imgur.com/U17o3yq.jpeg",
    popupImg: "https://i.imgur.com/U17o3yq.jpeg",
    bgImg: "https://i.imgur.com/cfdO7ES.jpeg",
    videoId: "UlNWt-SRIVQ",
    champion: false,
    title: "",
    nickname: "",
    alignment: "face",
    location: "Buffalo, New York",
    height: "5'7\"",
    weight: "200 lbs",
    stable: "",
    social: "@fswyoutub.javi",
    twitter: "@javihernandez2k",
    twitterUrl: "https://x.com/javihernandez2k",
    instagram: "javi.hernandez2k",
    instagramUrl: "https://www.instagram.com/javi.hernandez2k",
    theme: "El Drip — Natanael Cano",
    rating: 86,
    rival: "",
    endorsements: ["Chick-fil-A", "Diet Coke", "Subway"],
    commercials: [
      { brand: "Chick-fil-A", videoId: "9-jlkXMhShY" },
    ],
    bio: "Javi Hernandez carries the confidence of someone who has already proven he can win on the biggest nights. His past success gives him a natural composure under pressure, allowing him to stay relaxed while others panic. At times he can underestimate new threats, trusting his instincts a little too much, but when the moment truly demands it, Javi has the ability to flip the switch and remind everyone why his résumé speaks for itself.",
    superFinisher: "Springboard Frog Splash",
    superFinisherOrig: "Springboard Frog Splash",
    finisher1: "Operation Dragon 1",
    finisher1Orig: "Operation Dragon 1",
    finisher2: "Frog Splash 8",
    finisher2Orig: "Frog Splash 8",
    signatures: ["Basement Dropkick", "Superkick 13"],
    movies: [
      { title: "Street Fighter", released: "March 2026", videoId: "raPQD-uwWL8", role: "Ryu" },
    ],
    record: { singlesW:1, singlesL:1, multiW:0, multiL:0, titleWins:0, titleDefenses:0 },
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"J1", result:"L", type:"Genesis Tournament Final", championship:null, ranked:false, rankPos:null },
    { show:"FSW 51: Victory", opponent:"—", result:"W", type:"Debut — Genesis Tournament R1", championship:null, ranked:false, rankPos:null },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "St. Peter Reyes",
    incomplete: false,
    img: "https://i.imgur.com/XTIZE4a.jpeg",
    popupImg: "https://i.imgur.com/XTIZE4a.jpeg",
    bgImg: "https://i.imgur.com/We7TK6s.jpeg",
    videoId: "krhYuiqwPBQ",
    champion: false,
    title: "#1 Contender — FSW Supreme Championship",
    nickname: "Vaquero",
    alignment: "face",
    location: "Puerto Rico",
    height: "6'0\"",
    weight: "215 lbs",
    stable: "",
    social: "@fswyoutub.stpeter",
    twitter: "",
    instagram: "reyes.caw",
    instagramUrl: "https://www.instagram.com/reyes.caw",
    theme: "VERDE MENTA — Rauw Alejandro",
    rating: 91,
    rival: "William Kennedy · Aries Santiago",
    endorsements: ["Ringfizz", "Johnnie Walker"],
    bio: "St. Peter Reyes carries himself like judgment made flesh. Calm, unreadable, and spiritually composed, he does not chase chaos or applause; he waits for the moment when his presence alone shifts the room. St. Peter does not fight with anger but with conviction, dismantling opponents methodically as if delivering a verdict that was already decided long before the bell rang.",
    superFinisher: "Top Rope Perrero Powerbomb",
    superFinisherOrig: "Avalanche Powerbomb",
    finisher1: "Perrero Powerbomb",
    finisher1Orig: "Crucifix Jumping Powerbomb",
    finisher2: "SanDeVistan",
    finisher2Orig: "Footstomp",
    signatures: [["German Suplex", "Incoming!"], ["Butterfly DDT", "Snakebite"]],
    debut: "FSW 37: Fight for Survival",
    record: { singlesW:2, singlesL:1, multiW:1, multiL:0, titleWins:1, titleDefenses:0 },
    titleHistory: [
      { title: "FSW Supreme Championship", event: "FSW 37: Fight for Survival", date: "5.11.24" },
    ],
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Aries Santiago", result:"W", type:"Singles", championship:null, ranked:true, rankPos:10 },
    { show:"FSW 51: Victory", opponent:"William Kennedy", result:"W", type:"Singles — #1 Contender", championship:null, ranked:true, rankPos:10 },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "Kyle Vance",
    incomplete: false,
    img: "https://i.imgur.com/wtvvzLD.jpeg",
    popupImg: "https://i.imgur.com/wtvvzLD.jpeg",
    bgImg: "https://i.imgur.com/UqZSVHC.jpeg",
    videoId: "scDk9revJKI",
    champion: true,
    title: "FSW Mayhem Champion",
    nickname: "Next Level",
    alignment: "face",
    location: "Phoenix, AZ",
    height: "5'9\"",
    weight: "174 lbs",
    stable: "",
    social: "@fswyoutub.kyle",
    twitter: "",
    instagram: "",
    theme: "Harlem — New Politics",
    rating: 87,
    rival: "Derrick Maximus",
    endorsements: ["Carl's Jr", "Skechers", "Vitamin Water"],
    commercials: [
      { brand: "Carl's Jr", videoId: "IVEVPS3L5-M" },
    ],
    commercials: [
      { brand: "Carl's Jr", videoId: "IVEVPS3L5-M" },
    ],
    bio: "Kyle Vance is raw heart in a world full of politics. He fights with visible emotion, pushing through exhaustion and doubt because quitting simply is not in him. Kyle does not scheme or posture; he absorbs punishment, learns from it, and comes back harder, making him dangerous not because he is the loudest in the room, but because he refuses to stay down.",
    superFinisher: "Fall of the Apex",
    superFinisherOrig: "Phoenix 630 Senton",
    finisher1: "Cyclone Crash",
    finisher1Orig: "Corkscrew Forearm Smash",
    finisher2: "Sky Vance Spiral",
    finisher2Orig: "Corkscrew Shooting Star Press",
    signatures: [["Twist of Fate", "Vance Verdict"], ["Da Shout Out", "Loudmouth Lariat"]],
    movies: [
      { title: "Street Fighter", released: "March 2026", videoId: "raPQD-uwWL8", role: "Luke" },
    ],
    record: { singlesW:2, singlesL:0, multiW:0, multiL:0, titleWins:1, titleDefenses:0 },
        titleHistory: [
      { title: "FSW Mayhem Championship", event: "FSW 51: Victory", date: "19.12.25", label: "Claimed" },
    ], titleHistory: [
      { title: "FSW Mayhem Championship", event: "FSW 51: Victory", date: "19.12.25", label: "Claimed" },
    ],
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Derrick Maximus", result:"W", type:"Singles", championship:"FSW Mayhem Championship", ranked:true, rankPos:5 },
    { show:"FSW 51: Victory", opponent:"Max Milli (debut)", result:"W", type:"Singles", championship:"FSW Mayhem Championship", ranked:true, rankPos:5 },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "Derrick Maximus",
    incomplete: false,
    img: "https://i.imgur.com/Y00Je4M.jpeg",
    popupImg: "https://i.imgur.com/Y00Je4M.jpeg",
    bgImg: "https://i.imgur.com/oXdCuGu.jpeg",
    videoId: "PeA39_QONno",
    champion: false,
    title: "",
    nickname: "The Unconquered, Self-Crowned Malefactor",
    alignment: "heel",
    location: "Beverly Hills, CA",
    height: "6'0\"",
    weight: "198 lbs",
    stable: "Son of the Owner of FSW",
    social: "@fswyoutub.derrick",
    twitter: "@der_maximus",
    twitterUrl: "https://x.com/der_maximus",
    instagram: "",
    theme: "Sirius — Dartul",
    rating: 88,
    rival: "Kyle Vance · Shibata Reyes",
    allies: "Jaelyn Garcia",
    endorsements: ["Calvin Klein", "Cosmic Energy Drink", "Toyota", "Y by YSL", "Nike", "Crocs"],
    movies: [
      { title: "Street Fighter", released: "March 2026", videoId: "raPQD-uwWL8", role: "Ken" },
      { title: "Street Reckoning", released: "January 2026", videoId: "xbF1zY0OJMM", role: "Marcus Cole" },
      { title: "Monster Hunter", released: "December 2025", videoId: "jceTfYweR2o", role: "Lt. Artemis" },
      { title: "Black Hawk Dawn", released: "September 2025", videoId: "mUGRFSlRdlc", role: "Sgt. Holt" },
    ],
    commercials: [
      { brand: "Y by YSL", videoId: "7BWUwQ8IupE" },
      { brand: "Y by YSL", videoId: "um5KZT9KWOs" },
      { brand: "Calvin Klein", videoId: "ySlxDOBkokI" },
      { brand: "Toyota", videoId: "RmU9wh4fsYA" },
      { brand: "Crocs", videoId: "lDXs394eSrc" },
      { brand: "Monster Hunter", videoId: "_6NgtXb0VRo" },
    ],
    bio: "Derrick Maximus is ambition wrapped in entitlement, a man who carries legacy on his shoulders whether he admits it or not. Sharp, composed, and calculating, he hides insecurity behind confidence, moving with the precision of someone who believes the spotlight was always meant for him. Derrick does not explode like others; he pressures, manipulates, and outthinks, proving that control can be more dangerous than rage.",
    finisher1: "Maximum Odds",
    finisher1Orig: "Eight Second Ride",
    signatures: [["Dragon Slayer", "The Big Red"]],
    debut: "FSW 1: Maximum",
    titleHistory: [
      { title: "FSW Mayhem Championship", event: "FSW 48: Unfinished Business", date: "29.12.24" },
    ],
    record: { singlesW:1, singlesL:4, multiW:1, multiL:1, titleWins:1, titleDefenses:0 },
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Kyle Vance", result:"L", type:"Singles", championship:"FSW Mayhem Championship", ranked:true, rankPos:1 },
    { show:"FSW 51: Victory", opponent:"Shibata Reyes", result:"L", type:"Singles — DQ", championship:null, ranked:true, rankPos:1 },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"Return segment", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "Damian Rage",
    incomplete: false,
    img: "https://i.imgur.com/YcvmZnv.jpeg",
    popupImg: "https://i.imgur.com/YcvmZnv.jpeg",
    bgImg: "https://i.imgur.com/V896Syz.jpeg",
    videoId: "-LuYgWiFvHk",
    champion: false,
    title: "",
    nickname: "The Destroyer",
    alignment: "heel",
    location: "Milwaukee, WI",
    height: "6'0\"",
    weight: "245 lbs",
    stable: "Leader of The Syndicate",
    social: "@fswyoutube.damian",
    twitter: "",
    instagram: "",
    theme: "Violence No Matter What",
    rating: 86,
    rival: "Travis Valentine · KJ Hunter",
    allies: "Brittany Black · Vincent Omen",
    endorsements: ["Hot Pockets"],
    commercials: [
      { brand: "Hot Pockets", videoId: "u7ekKBb532c" },
    ],
    bio: "Damian Rage is controlled aggression barely held together by discipline. He does not talk much because he does not need to. The tension in his posture says enough. When he moves, it is direct and punishing, like every strike is personal, and once he locks onto a target, he does not stop until something breaks, physically or psychologically.",
    superFinisher: "DevilDriver",
    superFinisherOrig: "Electric Chair Driver",
    finisher1: "Lucifer's Downfall",
    finisher1Orig: "Pop Up Powerbomb 2",
    finisher2: "End of Days",
    finisher2Orig: "End of Days",
    signatures: [["The Disasterpiece", "Lifting Double Underhook"], ["Jumping Complete Shot", "JCS"]],
    debut: "FSW 19: Nemesis",
    record: { singlesW:2, singlesL:1, multiW:2, multiL:3, titleWins:1, titleDefenses:1 },
    titleHistory: [
      { title: "FSW Tag Team Championship", event: "FSW 20: Thrilla in Manila (Night 1)", date: "8.23.23" },
    ],
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"CJ Moore", result:"W", type:"FSW First-Class Championship", championship:"FSW First-Class Championship", ranked:false, rankPos:null },
    { show:"FSW 51: Victory", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "Alexa Rivera",
    incomplete: false,
    img: "https://i.imgur.com/kdvqxwt.jpeg",
    popupImg: "https://i.imgur.com/kdvqxwt.jpeg",
    bgImg: "https://i.imgur.com/mvIONnO.jpeg",
    videoId: "45-UN44oRJo",
    champion: true,
    title: "FSW Diamond Champion",
    nickname: "The Deadline",
    alignment: "face",
    location: "Buffalo, New York",
    height: "5'6\"",
    weight: "210 lbs",
    stable: "",
    social: "@fswyoutub.alexa",
    twitter: "",
    instagram: "",
    theme: "Queen — Loren Gray",
    rating: 88,
    rival: "Ivy Page · Brittany Black",
    endorsements: ["State Farm"],
    commercials: [
      { brand: "State Farm", videoId: "QshZDbNOYlk" },
    ],
    bio: "Alexa Rivera moves with quiet intensity, the kind that doesn't need volume to command attention. She's calculated and emotionally controlled, but underneath that composure is a competitive fire that refuses to be overshadowed by alliances or expectations. Alexa doesn't beg for the spotlight — she positions herself so precisely that when the moment arrives, it feels inevitable.",
    debut: "FSW 51: Victory",
    record: { singlesW:2, singlesL:0, multiW:0, multiL:0, titleWins:1, titleDefenses:0 },
    titleHistory: [
      { title: "FSW Diamond Championship", event: "FSW 52: Maximum", date: "12.02.26" },
    ],
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Ivy Page", result:"W", type:"Singles", championship:"FSW Diamond Championship", ranked:true, rankPos:4 },
    { show:"FSW 51: Victory", opponent:"—", result:"—", type:"Debut", championship:null, ranked:false, rankPos:null },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null }
  ],
  },

  {
    name: "William Kennedy",
    incomplete: false,
    img: "https://i.imgur.com/mbVuj2x.jpg",
    popupImg: "https://i.imgur.com/mbVuj2x.jpg",
    bgImg: "https://i.imgur.com/XalTUSB.jpg",
    videoId: "ICNOh67FsRA",
    videoUrl: "https://drive.google.com/file/d/1FacUr85dReqEHuFq_zOorAE6Z2sJ9fwG/view?usp=sharing",
    champion: false,
    title: "#1 Contender — Supreme Championship",
    nickname: "The Real Deal · The Detroit Playa",
    alignment: "heel",
    location: "Detroit, Michigan",
    height: "6'10\"",
    weight: "275 lbs",
    stable: "",
    social: "@fswyoutub.william",
    twitter: "@WillKennedy2K",
    twitterUrl: "https://x.com/WillKennedy2K",
    instagram: "thewilliamkennedy2k",
    instagramUrl: "https://www.instagram.com/thewilliamkennedy2k",
    theme: "Untouchable (Swizz Beatz Remix) — 2Pac",
    rating: 89,
    rival: "St. Peter Reyes",
    endorsements: ["Adidas", "Rolex"],
    commercials: [
      { brand: "Adidas", videoId: "XLKFHC9JY1I" },
    ],
    movies: [
      { title: "Twisted Metal", released: "July 2023", videoId: "55E5bESt1d4", role: "Agent Stone" },
    ],
    bio: "William Kennedy carries himself like a man who already knows the ending — and assumes it favors him. Cold, deliberate, and emotionally restrained, he doesn't waste energy on theatrics or outbursts; every word and movement feels measured, like a chess player thinking three moves ahead. Where others chase the spotlight, William controls the atmosphere, preferring psychological pressure over chaos, and letting silence do more damage than shouting ever could.",
    superFinisher: "Lights Out",
    superFinisherOrig: "Cyclone Suplex",
    finisher1: "The Will-Killer",
    finisher1Orig: "Torture Rack Back Stabber 1",
    finisher2: "RDS (Real Deal Sault)",
    finisher2Orig: "Diving Moonsault 3",
    signatures: [["Sit-Out Gourdbuster","Dealbreaker"], ["Wendy Bomb","Will Bomb"]],
    movies: [
      { title: "Street Fighter", released: "March 2026", videoId: "raPQD-uwWL8" , role: "T. Hawk" },
    ],
    record: { singlesW:2, singlesL:2, multiW:0, multiL:1, titleWins:0, titleDefenses:0 },
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Aries Santiago", result:"L", type:"Singles — #1 Contender", championship:null, ranked:false, rankPos:null },
    { show:"FSW 51: Victory", opponent:"St. Peter Reyes", result:"L", type:"Singles", championship:null, ranked:true, rankPos:4 },
    { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"—", championship:null, ranked:false, rankPos:null }
  ],
  },
  {
    name: "Kendrick Montana",
    incomplete: false,
    img: "https://i.imgur.com/5kqtFWZ.jpeg",
    popupImg: "https://i.imgur.com/5kqtFWZ.jpeg",
    bgImg: "https://i.imgur.com/xDY6KAR.jpeg",
    videoId: "tzmcSro1j00",
    alignment: "face",
    champion: false,
    title: "#1 Contender — FSW Ultima Championship",
    nickname: "Prince of the Rose",
    location: "Santo Domingo, Dominican Republic",
    height: "6'0\"",
    weight: "210 lbs",
    stable: "",
    social: "@fswyoutub2.kendrick",
    twitter: "@reallynotken",
    instagram: "kenny.blcc",
    theme: "Guiding Light — Caskets",
    rating: 88,
    rival: "Shibata Reyes",
    endorsements: ["Gatorade"],
    commercials: [
      { brand: "Gatorade", videoId: "k4uTXGL6KrI" },
    ],
    bio: "Kendrick Montana is pure impulse wrapped in pride. With fire in his eyes, he reacts before he thinks, driven by ego, insecurity, and a desperate need to prove he belongs at the top. Kendrick doesn't calculate consequences — he explodes, and only afterward tries to justify the damage he's caused.",
    superFinisher: "From the Heavens",
    superFinisherOrig: "Burning Hammer",
    finisher1: "Divinity Within",
    finisher1Orig: "Shooting Star Press",
    finisher2: "FTH V2",
    finisher2Orig: "Burning Hammer",
    signatures: [["The Devil Inside","Naibu no Akuma"], ["Flying Knee","Deadeye"]],
    movies: [
      { title: "Street Fighter", released: "March 2026", videoId: "raPQD-uwWL8", role: "Akuma" },
    ],
    record: { singlesW:1, singlesL:1, multiW:0, multiL:2, titleWins:0, titleDefenses:0 },
  recentMatches:[
    { show:"FSW 52: Maximum", opponent:"Shibata Reyes", result:"W", type:"Singles", championship:"FSW Ultima Championship", ranked:true, rankPos:2 },
    { show:"FSW 51: Victory", opponent:"—", result:"—", type:"Storyline segment", championship:null, ranked:true, rankPos:2 },
    { show:"FSW 50: Nemesis", opponent:"Aric Myers", result:"L", type:"Multi-Man", championship:null, ranked:true, rankPos:2 }
  ],
  },
  // { name:"Kyle Vance", img:"", videoId:"ID", champion:false, title:"", location:"", height:"", weight:"", stable:"", social:"", bio:"" },
];

// Ivy Page match history (standalone entry until added to full roster)
const ivyPageMatches = [
  { show:"FSW 52: Maximum", opponent:"Alexa Rivera", result:"L", type:"Singles", championship:"FSW Diamond Championship", ranked:true, rankPos:7 },
  { show:"FSW 51: Victory", opponent:"—", result:"W", type:"Title Win", championship:"FSW Diamond Championship", ranked:true, rankPos:8 },
  { show:"FSW 50: Nemesis", opponent:"—", result:"—", type:"Segment", championship:null, ranked:false, rankPos:null },
];
